# fly.toml app configuration file generated for full-stack-open-pokedex-dark-river-4380 on 2024-12-02T23:09:56+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
app = "full-stack-open-pokedex-dark-river-4380"
primary_region = "arn"

[env]
  PORT = "3000"

[processes]
  web = "node app.js"


[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[vm]]
  size = "shared-cpu-1x"
